/*
Copyright (c) 2006-2008, The University of Manchester, UK.

This file is part of PsyGrid.

PsyGrid is free software: you can redistribute it and/or modify
it under the terms of the GNU Lesser General Public License as 
published by the Free Software Foundation, either version 3 of 
the License, or (at your option) any later version.

PsyGrid is distributed in the hope that it will be useful,
but WITHOUT ANY WARRANTY; without even the implied warranty of
MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
GNU Lesser General Public License for more details.

You should have received a copy of the GNU Lesser General Public 
License along with PsyGrid.  If not, see <http://www.gnu.org/licenses/>.
*/

package org.psygrid.common.email;

import java.util.ArrayList;
import java.util.List;
import java.util.Map;

/**
 * An Email waiting to be sent, to notify of a randomisation event
 * 
 * @author Bill Vance
 * 
 * @hibernate.class table="t_queued_emails"
 */
public class QueuedEmail {

	/**
	 * Unique identifier, generated by the Hibernate framework
	 */
	protected Long id;
	
	/**
	 * The email to send
	 */
	private String subject;
	private String body;

	/**
	 * The email addresses of the people having roles that the email is to be sent to.
	 */
	private List<String> bccAddresses = new ArrayList<String>();

	//values that are specified in applicationConfig.xml file
	private String fromAddress = null;
	private String toAddress   = null;


	public QueuedEmail() {
	}


	/**
	 * Get the unique identifier, generated by the Hibernate framework
	 * 
	 * @return The unique identifier
	 * 
	 * @hibernate.id column = "c_id" 
	 * 			     generator-class="native"
	 */
	public Long getId() {
		return id;
	}


	public void setId(Long id) {
		this.id = id;
	}

	/**
	 * @return the body
	 * 
	 * @hibernate.property column="c_body" type="text" length="4096"
	 */
	public String getBody() {
		return body;
	}

	/**
	 * @param body the body to set
	 */
	public void setBody(String body) {
		this.body = body;
	}


	/**
	 * @return the subject
	 * 
	 * @hibernate.property column="c_subject"
	 */
	public String getSubject() {
		return subject;
	}

	/**
	 * @param subject the subject to set
	 */
	public void setSubject(String subject) {
		this.subject = subject;
	}


	/**
	 * @return the toAddresses
	 * 
	 * @hibernate.property column="c_to_address"
	 */
	public String getToAddress() {
		return toAddress;
	}

	/**
	 * @param toAddress
	 *            the toAddresses to set
	 */
	public void setToAddress(String toAddress) {
		this.toAddress = toAddress;
	}

	/**
	 * @return the bccAddresses
	 * 
	 * @hibernate.list cascade="all" table="t_bcc_addresses" lazy="false"
	 * @hibernate.key column="c_queued_email_id" not-null="true"
	 * @hibernate.element column="c_bcc_address"
	 *                    type="string"
	 * @hibernate.list-index column="c_index"
	 */
	public List<String> getBccAddresses() {
		return bccAddresses;
	}

	/**
	 * Set the bccAddresses to send the email to. Use this
	 * rather than the to address when sending to multiple
	 * recipients.
	 * 
	 * @param bccAddresses
	 */
	public void setBccAddresses(List<String> bccAddresses) {
		this.bccAddresses = bccAddresses;
	}

	/**
	 * @return the fromAddress
	 * 
	 * @hibernate.property column="c_from_address"
	 */
	public String getFromAddress() {
		return fromAddress;
	}

	/**
	 * @param fromAddress the fromAddress to set
	 */
	public void setFromAddress(String fromAddress) {
		this.fromAddress = fromAddress;
	}


}
