-- This patch makes the necessary schema changes to support the secure-export feature
-- The patch must be applied to all databases deployed from revisions prior to (//TODO:EXPORT_SECURITY - #addrevno#)

alter table t_datasets add column c_export_security_active smallint;
alter table t_elements add column c_export_security varchar(255);
create table t_entry_output_transformers (c_entry_id bigint not null, c_transformer_id bigint not null, c_index integer not null, primary key (c_entry_id, c_index));
create table t_export_action (c_id bigint generated by default as identity, c_version integer not null, c_security_tag varchar(255), c_export_action varchar(255), c_exportreq_id bigint, c_index integer, primary key (c_id));
alter table t_entry_output_transformers add constraint FK459169A0E7A2E711 foreign key (c_entry_id) references t_basic_entrys;
alter table t_entry_output_transformers add constraint FK459169A0F05319CD foreign key (c_transformer_id) references t_transformers;
alter table t_export_action add constraint FKB2B88C9666DD1399 foreign key (c_exportreq_id) references t_export_requests;
update t_datasets set c_export_security_active=0;
