-- Patch to add tables for reporting functionality
create table t_chart_types (c_chart_id bigint not null, c_type varchar(255) not null, c_index integer not null, primary key (c_chart_id, c_index));
create table t_charts (c_id bigint not null, c_title varchar(255), primary key (c_id));
create table t_grp_summ_charts (c_id bigint not null, primary key (c_id));
create table t_grpsmchrt_groups (c_chart_id bigint not null, c_group_id bigint not null, c_index integer not null, primary key (c_chart_id, c_index));
create table t_mgmt_charts (c_id bigint not null, c_report_id bigint not null, c_index integer, primary key (c_id));
create table t_mgmt_reports (c_id bigint not null, c_role varchar(255), c_with_raw_data smallint, primary key (c_id));
create table t_mgmtrep_groups (c_report_id bigint not null, c_group_id bigint not null, c_index integer not null, primary key (c_report_id, c_index));
create table t_prj_summ_charts (c_id bigint not null, primary key (c_id));
create table t_rec_reports (c_id bigint not null, primary key (c_id));
create table t_reports (c_id bigint not null, c_dataset_id bigint not null, c_title varchar(255), primary key (c_id));
create table t_simple_chart_items (c_id bigint not null, c_doc_occ_id bigint not null, c_entry_id bigint not null, c_sec_occ_id bigint not null, c_options varchar(255), c_label_options varchar(255), c_sim_chart_id bigint not null, c_index integer, primary key (c_id));
create table t_simple_charts (c_id bigint not null, c_report_id bigint not null, c_index integer, primary key (c_id));
create table t_user_summ_charts (c_id bigint not null, primary key (c_id));
create table t_usrsmchrt_groups (c_chart_id bigint not null, c_group_id bigint not null, c_index integer not null, primary key (c_chart_id, c_index));
alter table t_chart_types add constraint FKD1D1058DB58A20A7 foreign key (c_chart_id) references t_charts;
alter table t_charts add constraint FK624F768049CB0AD7 foreign key (c_id) references t_persistents;
alter table t_grp_summ_charts add constraint FK66FC2D8D93AC95E3 foreign key (c_id) references t_mgmt_charts;
alter table t_grpsmchrt_groups add constraint FK4587A8B8373B9A4D foreign key (c_group_id) references t_groups;
alter table t_grpsmchrt_groups add constraint FK4587A8B841A3B593 foreign key (c_chart_id) references t_grp_summ_charts;
alter table t_mgmt_charts add constraint FK20AAAA48E24D7DA6 foreign key (c_id) references t_charts;
alter table t_mgmt_charts add constraint FK20AAAA481C5E3690 foreign key (c_report_id) references t_mgmt_reports;
alter table t_mgmt_reports add constraint FK9DB8A2C7B65FE7A foreign key (c_id) references t_reports;
alter table t_mgmtrep_groups add constraint FK80D57A62373B9A4D foreign key (c_group_id) references t_groups;
alter table t_mgmtrep_groups add constraint FK80D57A621C5E3690 foreign key (c_report_id) references t_mgmt_reports;
alter table t_prj_summ_charts add constraint FKF8A0C2D093AC95E3 foreign key (c_id) references t_mgmt_charts;
alter table t_rec_reports add constraint FKC16171C57B65FE7A foreign key (c_id) references t_reports;
alter table t_reports add constraint FKFCD044F449CB0AD7 foreign key (c_id) references t_persistents;
alter table t_reports add constraint FKFCD044F4D0BFC2CD foreign key (c_dataset_id) references t_datasets;
alter table t_simple_chart_items add constraint FK26F542BD590825BD foreign key (c_sim_chart_id) references t_simple_charts;
alter table t_simple_chart_items add constraint FK26F542BD49CB0AD7 foreign key (c_id) references t_persistents;
alter table t_simple_chart_items add constraint FK26F542BD9C24716D foreign key (c_entry_id) references t_entrys;
alter table t_simple_chart_items add constraint FK26F542BD43F87002 foreign key (c_sec_occ_id) references t_sec_occs;
alter table t_simple_chart_items add constraint FK26F542BDD307CAA3 foreign key (c_doc_occ_id) references t_doc_occs;
alter table t_simple_charts add constraint FKF3F0FAF7E24D7DA6 foreign key (c_id) references t_charts;
alter table t_simple_charts add constraint FKF3F0FAF77F46C79E foreign key (c_report_id) references t_rec_reports;
alter table t_user_summ_charts add constraint FKD8BC49A993AC95E3 foreign key (c_id) references t_mgmt_charts;
alter table t_usrsmchrt_groups add constraint FKB918C869373B9A4D foreign key (c_group_id) references t_groups;
alter table t_usrsmchrt_groups add constraint FKB918C869F40654CA foreign key (c_chart_id) references t_user_summ_charts;
