alter table t_charts add column c_range_axis_label varchar(255);
alter table t_charts add column c_use_percentages smallint default 0;
alter table t_reports add column c_template smallint default 1;
alter table t_rec_reports add column c_record_id bigint;
create table t_record_charts (c_id bigint not null, c_report_id bigint not null, c_index integer not null, primary key (c_id));
create table t_recruitment_progress_charts (c_id bigint not null, c_end_date timestamp, c_start_date timestamp, primary  key (c_id));
create table t_recuitmentchrt_groups (c_chart_id bigint not null, c_group_id bigint not null, c_index integer not null,  primary key (c_chart_id, c_index));
drop table t_simple_chart_items;
drop table t_simple_charts;
create table t_simple_chart_items (c_id bigint not null, c_doc_occ_id bigint not null, c_entry_id bigint not null, c_sec_occ_id bigint not null, c_options varchar(255), c_label_options varchar(255), c_simple_chart_row_id bigint not null, c_index integer, primary key (c_id));
create table t_simple_chart_rows (c_id bigint not null, c_label varchar(255), c_label_type varchar(255), c_rec_chart_id  bigint, c_index integer, primary key (c_id));
create table t_simple_charts (c_id bigint not null, primary key (c_id));
create table t_targets (c_target_id bigint not null, c_value integer, c_month timestamp not null, primary key (c_target_id, c_month));
create table t_trends_charts (c_id bigint not null, c_end_date timestamp, c_start_date timestamp, c_trend_report_id bigint not null, c_show_totals smallint, c_trends_index integer, primary key (c_id));
create table t_trends_gantt_charts (c_id bigint not null, primary key (c_id));
create table t_trends_reports (c_id bigint not null, primary key (c_id));
create table t_trendschrt_groups (c_chart_id bigint not null, c_group_id bigint not null, c_index integer not null, primary key (c_chart_id, c_index));
create table t_ukcrn_summ_charts (c_id bigint not null, c_end_date timestamp, c_start_date timestamp, primary key (c_id));
create table t_trends_chart_row (c_id bigint not null, c_summary_type varchar(255), c_trends_chart_id bigint not null, c_index integer, primary key (c_id));

alter table t_rec_reports add constraint FKC16171C555D83587 foreign key (c_record_id) references t_records;
alter table t_record_charts add constraint FK33285F7898EE1A54 foreign key (c_id) references t_simple_charts; 
alter table t_recuitmentchrt_groups add constraint FKCE948A33373B9A4D foreign key (c_group_id) references t_groups;
alter table t_record_charts add constraint FK33285F787F46C79E foreign key (c_report_id) references t_rec_reports;
alter table t_recruitment_progress_charts add constraint FKA1C2B4B993AC95E3 foreign key (c_id) references t_mgmt_charts ;
alter table t_recuitmentchrt_groups add constraint FKCE948A33114AAFFC foreign key (c_chart_id) references t_recruitment_progress_charts;
alter table t_simple_chart_items add constraint FK26F542BD77D8996F foreign key (c_simple_chart_row_id) references t_simple_chart_rows;
alter table t_simple_chart_rows add constraint FK4B98533C15FDDAE5 foreign key (c_rec_chart_id) references t_record_charts;
alter table t_simple_chart_rows add constraint FK4B98533C49CB0AD7 foreign key (c_id) references t_persistents;
alter table t_targets add constraint FK5FE1B43748F50031 foreign key (c_target_id) references t_recruitment_progress_charts;
alter table t_trends_chart_row add constraint FKBD668BDB875F2334 foreign key (c_id) references t_simple_chart_rows;
alter table t_trends_chart_row add constraint FKBD668BDB9F663A82 foreign key (c_trends_chart_id) references t_trends_charts;
alter table t_trends_charts add constraint FKA42755B3DB00EE1 foreign key (c_trend_report_id) references t_trends_reports;
alter table t_trends_charts add constraint FKA42755B398EE1A54 foreign key (c_id) references t_simple_charts;
alter table t_trends_gantt_charts add constraint FK4332D57EC333F410 foreign key (c_id) references t_trends_charts;
alter table t_trends_reports add constraint FKF5F44C217B65FE7A foreign key (c_id) references t_reports;
alter table t_trendschrt_groups add constraint FK8694AC6B373B9A4D foreign key (c_group_id) references t_groups;
alter table t_ukcrn_summ_charts add constraint FK295FF0F193AC95E3 foreign key (c_id) references t_mgmt_charts;
