alter table t_charts add column c_range_axis_label varchar(255);
alter table t_charts add column c_use_percentages bit;
alter table t_reports add column c_template bit default 1;
alter table t_rec_reports add column c_record_id bigint;
create table t_record_charts (c_id bigint not null, c_report_id bigint not null, c_index integer not null, primary key (c_id)) type=InnoDB;
create table t_recruitment_progress_charts (c_id bigint not null, c_end_date timestamp, c_start_date timestamp, primary  key (c_id)) type=InnoDB;
create table t_recuitmentchrt_groups (c_chart_id bigint not null, c_group_id bigint not null, c_index integer not null,  primary key (c_chart_id, c_index)) type=InnoDB;
drop table t_simple_chart_items;
drop table t_simple_charts;
create table t_simple_chart_rows (c_id bigint not null, c_label varchar(255), c_label_type varchar(255), c_rec_chart_id bigint, c_index integer, primary key (c_id)) type=InnoDB;
 create table t_simple_chart_items (c_id bigint not null, c_doc_occ_id bigint not null, c_entry_id bigint not null, c_sec_occ_id bigint not null, c_options varchar(255), c_label_options varchar(255), c_simple_chart_row_id bigint not null, c_index integer, primary key (c_id)) type=InnoDB;
create table t_simple_charts (c_id bigint not null, primary key (c_id)) type=InnoDB;
 create table t_targets (c_target_id bigint not null, c_value integer, c_month timestamp not null, primary key (c_target_id, c_month)) type=InnoDB;
create table t_trends_chart_row (c_id bigint not null, c_summary_type varchar(255), c_trends_chart_id bigint not null, c_index integer, primary key (c_id)) type=InnoDB;
create table t_trends_charts (c_id bigint not null, c_end_date datetime, c_start_date datetime, c_trend_report_id bigint not null, c_show_totals bit, c_trends_index integer, primary key (c_id)) type=InnoDB;
create table t_trends_gantt_charts (c_id bigint not null, primary key (c_id)) type=InnoDB;
create table t_trends_reports (c_id bigint not null, primary key (c_id)) type=InnoDB;
create table t_trendschrt_groups (c_chart_id bigint not null, c_group_id bigint not null, c_index integer not null, primary key (c_chart_id, c_index)) type=InnoDB;
create table t_ukcrn_summ_charts (c_id bigint not null, c_end_date datetime, c_start_date datetime, primary key (c_id)) type=InnoDB;
