/*
Copyright (c) 2006-2008, The University of Manchester, UK.

This file is part of PsyGrid.

PsyGrid is free software: you can redistribute it and/or modify
it under the terms of the GNU Lesser General Public License as 
published by the Free Software Foundation, either version 3 of 
the License, or (at your option) any later version.

PsyGrid is distributed in the hope that it will be useful,
but WITHOUT ANY WARRANTY; without even the implied warranty of
MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
GNU Lesser General Public License for more details.

You should have received a copy of the GNU Lesser General Public 
License along with PsyGrid.  If not, see <http://www.gnu.org/licenses/>.
*/

package org.psygrid.data.export.dto;

/**
 * This class provides a mapping between security tags, and the required action for a particular user role.
 * 
 * @author William Vance
 *
 */
public class ExportSecurityActionMap {
	
	/**
	 * This is the string version of the security tag of the mapping - must be one of the values defined in ExportSecurityValues.
	 */
	private String securityTag; 
	
	/**
	 * This is the string version of the export action of the mapping - must be one of the values defined in DataExportActions.
	 */
	private String exportAction; 
	
    /**
	 * Unique identifier, generated by the Hibernate framework
	 */
	private Long id;
	
	/**
	 * Version, generated by the Hibernate framework
	 */
	private int version;
	
	/**
	 * 
	 * @param securityTag - string version of one of the values defined in ExportSecurityValues
	 */
	public void setSecurityTag(String securityTag){
		this.securityTag = securityTag;
	}
	
	/**
	 * 
	 * @return string version of one of the values defined in ExportSecurityValues
	 */
	public String getSecurityTag(){
		return this.securityTag;
	}
	
	/**
	 * 
	 * @param exportAction - string version of one of the values defined in DataExportActions
	 */
	public void setExportAction(String exportAction){
		this.exportAction = exportAction;
	}

	/**
	 * 
	 * @return the string version of one of the values defined in DataExportActions
	 */
	public String getExportAction(){
		return this.exportAction;
	}
	
	
	public Long getId() {
		return id;
	}

	public void setId(Long id) {
		this.id = id;
	}
	
	public int getVersion() {
		return version;
	}

	public void setVersion(int version) {
		this.version = version;
	}
	
	public org.psygrid.data.export.hibernate.ExportSecurityActionMap toHibernate(){
		org.psygrid.data.export.hibernate.ExportSecurityActionMap hESAM = new org.psygrid.data.export.hibernate.ExportSecurityActionMap();
		hESAM.setId(this.id);
		hESAM.setVersion(this.version);
		hESAM.setSecurityTag(this.securityTag);
		hESAM.setExportAction(this.exportAction);
		return hESAM;
	}

}
