/*
Copyright (c) 2006-2008, The University of Manchester, UK.

This file is part of PsyGrid.

PsyGrid is free software: you can redistribute it and/or modify
it under the terms of the GNU Lesser General Public License as 
published by the Free Software Foundation, either version 3 of 
the License, or (at your option) any later version.

PsyGrid is distributed in the hope that it will be useful,
but WITHOUT ANY WARRANTY; without even the implied warranty of
MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
GNU Lesser General Public License for more details.

You should have received a copy of the GNU Lesser General Public 
License along with PsyGrid.  If not, see <http://www.gnu.org/licenses/>.
 */
package org.psygrid.data.export.dto;



public class ExportDocument {
	/**
	 * Unique identifier, generated by the Hibernate framework
	 */
	private Long id;

	/**
	 * Version, generated by the Hibernate framework
	 */
	private int version;

	/**
	 * The id of the document occurrence to be exported
	 */
	private Long docOccId;

	/**
	 * The ids of the entries to be exported
	 */
	private long[] entryIds = new long[0];

	public Long getDocOccId() {
		return docOccId;
	}

	public void setDocOccId(Long docOccId) {
		this.docOccId = docOccId;
	}

	public long[] getEntryIds() {
		return entryIds;
	}

	public void setEntryIds(long[] entryIds) {
		this.entryIds = entryIds;
	}

	public Long getId() {
		return id;
	}

	public void setId(Long id) {
		this.id = id;
	}

	public int getVersion() {
		return version;
	}

	public void setVersion(int version) {
		this.version = version;
	}
	
	public org.psygrid.data.export.hibernate.ExportDocument toHibernate() {
		org.psygrid.data.export.hibernate.ExportDocument hED = new org.psygrid.data.export.hibernate.ExportDocument();
		
		hED.setId(this.id);
		hED.setVersion(this.version);
		hED.setDocOccId(this.docOccId);
		for (long id: this.entryIds) {
			hED.addEntryId(id);
		}
		
		return hED;
	}
}
