alter table t_bcc_addresses drop foreign key FK4067FF5AF5F8BC2D;
alter table t_queued_emails drop foreign key FK1F781C18B089F7BB;
alter table t_emails drop foreign key FK65FF7A82B089F7BB;

drop table t_bcc_addresses;
drop table t_emails;
drop table t_queued_emails;

create table t_bcc_addresses (c_queued_email_id bigint not null, c_bcc_address varchar(255), c_index integer not null, primary key (c_queued_email_id, c_index));
create table t_emails (c_id bigint generated by default as identity, c_subject varchar(255), c_body clob(4096), primary key (c_id));
create table t_queued_emails (c_id bigint generated by default as identity, c_body clob(4096), c_subject varchar(255), c_to_address varchar(255), c_from_address varchar(255), primary key (c_id));
alter table t_bcc_addresses add constraint FK4067FF5A8EEE139E foreign key (c_queued_email_id) references t_queued_emails;

